language: python

python:
  - "2.7"

virtualenv:
    system_site_packages: true
        - "2.7_with_system_site_packages"

before_install:
    - sudo apt-get update
    - sudo apt-get install scipy

install:
  - python setup.py install

script: nosetests
