language: python

python:
  - "2.7"


# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm


install:
  # install deps
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose
  # install channelworm
  - pip install -r requirements.txt

script: channelworm/manage.py test
    #nosetests (not sure what we're doing with this, so commenting it)

